### ISSUE TITLE
why I just can detect the car

### ISSUE THREAD

**Issue by xiaozialei** [QiangXie/libfaster_rcnn_cpp#2]
I have run the code successfully ,but why I just can detect the car. 
    string model_file = "/home/hxl/py-faster-rcnn/models/pascal_voc/VGG16/faster_rcnn_alt_opt/faster_rcnn_test.pt";
    string weights_file = "/home/hxl/py-faster-rcnn/data/faster_rcnn_models/VGG16_faster_rcnn_final.caffemodel";

**Comment by QiangXie** [comment]
Because I only use faster-rcnn to detect the vehicle, you can modify the value of "DETEC_CLS_NUM" (in include/faster_rcnn.hpp) to detect other objects.

**Comment by xiaozialei** [comment]
Thanks for your help.
